# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  driver: "gd"
  # your filter sets are defined here
  filter_sets:
    Extra_large:
      quality: 75
      filters:
        thumbnail:
          size: [ 1920,930 ]
          mode: outbound
    very_large:
      quality: 75
      filters:
        thumbnail:
          size: [ 518,642 ]
          mode: outbound
    large:
      quality: 75
      filters:
        thumbnail:
          size: [ 513, 635 ]
          mode: outbound
    medium:
      quality: 75
      filters:
        relative_resize:
          # given 50x40px, output 75x60px using "heighten" option
          heighten: 500
    small:
      quality: 75
      filters:
        relative_resize:
          # given 50x40px, output 75x60px using "heighten" option
          heighten: 100
    very_small:
      quality: 75
      filters:
        thumbnail:
          size: [ 50, 50 ]
          mode: outbound
    my_rotate:
      filters:
        rotate:
          angle: 0
    my_flip:
      filters:
        flip:
          axis: x