#!/bin/sh
rsync -av ./ shineaur@shineaurora.com:~/public_html/test --include=public/build --include=public/.htaccess --exclude-from=.gitignore --exclude=".*"  --exclude=.env
#ssh shineaur@shineaurora.com 'cd ~/public_html/shine_aurora && php bin/console cache:clear'