#!/bin/sh
rsync -av ./ genesjz7@genesistech-dz.com:~/public_html/shine_aurora --include=public/build --include=public/.htaccess --exclude-from=.gitignore --exclude=".*"  --exclude=.env
#ssh genesjz7@genesistech-dz.com 'cd ~/public_html/shine_aurora && php bin/console cache:clear'